#!/bin/bash

# Quick Test Commands for Jobs API Data Flow

echo "🚀 Quick Start Commands"
echo "======================="
echo ""
echo "1️⃣  Start dev server:"
echo "   npm run dev"
echo ""
echo "2️⃣  In another terminal, trigger ingestion via curl:"
echo "   curl -X POST http://localhost:3000/api/ingest/jobs/adzuna \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"where\": \"round rock tx\", \"maxPages\": 3}'"
echo ""
echo "3️⃣  Expected response:"
echo "   {\"ok\": true, \"created\": 45, \"updated\": 0, \"skipped\": 2}"
echo ""
echo "4️⃣  Then:"
echo "   - Go to http://localhost:3000/jobs"
echo "   - Open browser console (F12)"
echo "   - Refresh page (F5)"
echo "   - See all logs and data"
echo ""
echo "5️⃣  View in Payload CMS:"
echo "   http://localhost:3000/admin/collections/jobs"
echo ""
echo "======================="
echo ""
echo "Alternative: Click the blue button on jobs page instead of curl ✨"
